- name: Create a new environment (top level directory name)
  hosts: local
  gather_facts: no
  tasks:

  - fail:
      msg: "Please specify the environment name (use the env variable)"
    when: env is not defined

  - name: Create directory structure
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ env }}/group_vars/local"
    - "{{ env }}/public-files"
    - "{{ env }}/secret-files"

  - name: Create hosts file
    copy:
      dest: "{{ env }}/hosts"
      content: "[local]\nlocalhost ansible_connection=local env={{ env }}"

  - name: Create ansible.cfg file
    copy:
      dest: "{{ env }}/ansible.cfg"
      content: "[defaults]\ninventory = hosts\nvault_password_file = vault-password"

  - name: create variable names file "plaintextvars.yaml" in group_vars defining "plaintext_files" variable
    # This will also ensure there's a file in group_vars/local, so that Git will commit the directories
    # content is plaintext_files: "{{ secret_files }}"
    copy:
      dest: "{{ env }}/group_vars/local/plaintextvars.yaml"
      content: "plaintext_files: {{ '\"{{' }} secret_files {{ '}}\"' }}"

  - name: create SSH keypair for this environment's machines
    command: "ssh-keygen -f ~/.ssh/{{ env }}-key -N \"\""
    args:
      creates: "~/.ssh/{{ env }}-key"

  - name: copy private keys to secret-files directory
    copy:
      src: "{{ item }}"
      dest: "{{ env }}/secret-files/"
      mode: 0600
    with_items:
    - "~/.ssh/{{ env }}-key"

  - name: copy public keys to public-files directory
    copy:
      src: "{{ item }}"
      dest: "{{ env }}/public-files/"
    with_items:
    - "~/.ssh/{{ env }}-key.pub"

  - name: Create vault-password file with random password
    command: "true {{ lookup('password', env + '/vault-password chars=ascii_letters') }}"
    args:
      creates: "{{ env }}/vault-password"

  - include: roles/common/tasks/add-to-git.yaml
